#:property RestorePackagesWithLockFile=false

using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;

if (args.Length is < 2 or > 3)
{
    Console.Error.WriteLine("Usage: dotnet run --file scripts/verify-public-api.cs -- <assembly> <baseline> [--write]");
    return 1;
}

string assemblyPath = Path.GetFullPath(args[0]);
string baselinePath = Path.GetFullPath(args[1]);
bool write = args.Length == 3 && string.Equals(args[2], "--write", StringComparison.Ordinal);

if (args.Length == 3 && !write)
{
    Console.Error.WriteLine("Only --write is accepted as the optional third argument.");
    return 1;
}

using FileStream stream = File.OpenRead(assemblyPath);
using PEReader peReader = new(stream);
MetadataReader reader = peReader.GetMetadataReader();
List<string> actual = BuildSnapshot(reader);

if (write)
{
    Directory.CreateDirectory(Path.GetDirectoryName(baselinePath)!);
    File.WriteAllLines(
        baselinePath,
        [
            "# ReliableWebhooks public API type/member shape frozen for v0.1.0.",
            "# Generated by scripts/verify-public-api.cs. Do not edit without deliberate API review.",
            .. actual,
        ]);

    Console.WriteLine($"Public API baseline written: {baselinePath} ({actual.Count} entries)");
    return 0;
}

if (!File.Exists(baselinePath))
{
    throw new InvalidOperationException($"Public API baseline not found: {baselinePath}");
}

List<string> expected = File.ReadLines(baselinePath)
    .Where(static line => !string.IsNullOrWhiteSpace(line) && !line.StartsWith('#'))
    .Order(StringComparer.Ordinal)
    .ToList();

if (expected.SequenceEqual(actual, StringComparer.Ordinal))
{
    Console.WriteLine($"Public API snapshot validated: {actual.Count} entries.");
    return 0;
}

string[] added = actual.Except(expected, StringComparer.Ordinal).ToArray();
string[] removed = expected.Except(actual, StringComparer.Ordinal).ToArray();
Console.Error.WriteLine("Public API changed relative to the v0.1.0 baseline.");

foreach (string item in added)
{
    Console.Error.WriteLine($"+ {item}");
}

foreach (string item in removed)
{
    Console.Error.WriteLine($"- {item}");
}

return 2;

static List<string> BuildSnapshot(MetadataReader reader)
{
    List<string> entries = [];

    foreach (TypeDefinitionHandle handle in reader.TypeDefinitions)
    {
        if (!IsExternallyVisibleType(reader, handle))
        {
            continue;
        }

        TypeDefinition type = reader.GetTypeDefinition(handle);
        string typeName = GetTypeName(reader, handle);
        entries.Add($"T:{typeName}");

        foreach (MethodDefinitionHandle methodHandle in type.GetMethods())
        {
            MethodDefinition method = reader.GetMethodDefinition(methodHandle);
            if (!IsVisibleMethod(method.Attributes))
            {
                continue;
            }

            string name = reader.GetString(method.Name);
            int parameterCount = 0;

            foreach (ParameterHandle parameterHandle in method.GetParameters())
            {
                if (reader.GetParameter(parameterHandle).SequenceNumber > 0)
                {
                    parameterCount++;
                }
            }

            int genericArity = method.GetGenericParameters().Count;
            entries.Add($"M:{typeName}.{name}`{genericArity}/{parameterCount}");
        }

        foreach (FieldDefinitionHandle fieldHandle in type.GetFields())
        {
            FieldDefinition field = reader.GetFieldDefinition(fieldHandle);
            if (!IsVisibleField(field.Attributes))
            {
                continue;
            }

            entries.Add($"F:{typeName}.{reader.GetString(field.Name)}");
        }
    }

    entries.Sort(StringComparer.Ordinal);
    return entries;
}

static bool IsExternallyVisibleType(MetadataReader reader, TypeDefinitionHandle handle)
{
    TypeDefinition type = reader.GetTypeDefinition(handle);
    TypeAttributes visibility = type.Attributes & TypeAttributes.VisibilityMask;

    if (visibility == TypeAttributes.Public)
    {
        return true;
    }

    if (visibility is not (TypeAttributes.NestedPublic or TypeAttributes.NestedFamily or TypeAttributes.NestedFamORAssem))
    {
        return false;
    }

    TypeDefinitionHandle parent = type.GetDeclaringType();
    return !parent.IsNil && IsExternallyVisibleType(reader, parent);
}

static bool IsVisibleMethod(MethodAttributes attributes)
{
    MethodAttributes access = attributes & MethodAttributes.MemberAccessMask;
    return access is MethodAttributes.Public or MethodAttributes.Family or MethodAttributes.FamORAssem;
}

static bool IsVisibleField(FieldAttributes attributes)
{
    FieldAttributes access = attributes & FieldAttributes.FieldAccessMask;
    return access is FieldAttributes.Public or FieldAttributes.Family or FieldAttributes.FamORAssem;
}

static string GetTypeName(MetadataReader reader, TypeDefinitionHandle handle)
{
    TypeDefinition type = reader.GetTypeDefinition(handle);
    string name = reader.GetString(type.Name);
    TypeDefinitionHandle parent = type.GetDeclaringType();

    if (!parent.IsNil)
    {
        return $"{GetTypeName(reader, parent)}.{name}";
    }

    string ns = reader.GetString(type.Namespace);
    return string.IsNullOrEmpty(ns) ? name : $"{ns}.{name}";
}
