#:property RestorePackagesWithLockFile=false

using System.Globalization;
using System.Reflection;
using System.Runtime.Loader;

if (args.Length is < 2 or > 3)
{
    Console.Error.WriteLine("Usage: dotnet run --file scripts/verify-public-api.cs -- <assembly> <baseline> [--write]");
    return 1;
}

string assemblyPath = Path.GetFullPath(args[0]);
string baselinePath = Path.GetFullPath(args[1]);
bool write = args.Length == 3 && string.Equals(args[2], "--write", StringComparison.Ordinal);

if (args.Length == 3 && !write)
{
    Console.Error.WriteLine("Only --write is accepted as the optional third argument.");
    return 1;
}

List<string> actual;
var loadContext = new SnapshotLoadContext(assemblyPath);

try
{
    Assembly assembly = loadContext.LoadFromAssemblyPath(assemblyPath);
    actual = BuildSnapshot(assembly);
}
catch (ReflectionTypeLoadException exception)
{
    Console.Error.WriteLine("Unable to load the complete public API surface.");

    foreach (Exception? loaderException in exception.LoaderExceptions)
    {
        if (loaderException is not null)
        {
            Console.Error.WriteLine(loaderException.Message);
        }
    }

    return 3;
}
finally
{
    loadContext.Unload();
}

if (write)
{
    Directory.CreateDirectory(Path.GetDirectoryName(baselinePath)!);
    File.WriteAllLines(
        baselinePath,
        [
            "# ReliableWebhooks public API signatures frozen for v0.1.0.",
            "# Generated by scripts/verify-public-api.cs. Do not edit without deliberate API review.",
            .. actual,
        ]);

    Console.WriteLine($"Public API baseline written: {baselinePath} ({actual.Count} entries)");
    return 0;
}

if (!File.Exists(baselinePath))
{
    throw new InvalidOperationException($"Public API baseline not found: {baselinePath}");
}

List<string> expected = File.ReadLines(baselinePath)
    .Where(static line => !string.IsNullOrWhiteSpace(line) && !line.StartsWith('#'))
    .Order(StringComparer.Ordinal)
    .ToList();

if (expected.SequenceEqual(actual, StringComparer.Ordinal))
{
    Console.WriteLine($"Public API snapshot validated: {actual.Count} entries.");
    return 0;
}

string[] added = actual.Except(expected, StringComparer.Ordinal).ToArray();
string[] removed = expected.Except(actual, StringComparer.Ordinal).ToArray();
Console.Error.WriteLine("Public API changed relative to the v0.1.0 baseline.");

foreach (string item in added)
{
    Console.Error.WriteLine($"+ {item}");
}

foreach (string item in removed)
{
    Console.Error.WriteLine($"- {item}");
}

return 2;

static List<string> BuildSnapshot(Assembly assembly)
{
    const BindingFlags declaredMembers =
        BindingFlags.Public |
        BindingFlags.NonPublic |
        BindingFlags.Instance |
        BindingFlags.Static |
        BindingFlags.DeclaredOnly;

    List<string> entries = [];

    foreach (Type type in assembly.GetTypes().Where(IsExternallyVisible).OrderBy(FormatType, StringComparer.Ordinal))
    {
        entries.Add(FormatTypeEntry(type));

        foreach (ConstructorInfo constructor in type.GetConstructors(declaredMembers).Where(IsVisibleMethod))
        {
            entries.Add(FormatConstructorEntry(type, constructor));
        }

        foreach (MethodInfo method in type.GetMethods(declaredMembers).Where(IsVisibleMethod))
        {
            entries.Add(FormatMethodEntry(type, method));
        }

        foreach (FieldInfo field in type.GetFields(declaredMembers).Where(IsVisibleField))
        {
            entries.Add(FormatFieldEntry(type, field));
        }

        foreach (PropertyInfo property in type.GetProperties(declaredMembers))
        {
            string? entry = FormatPropertyEntry(type, property);
            if (entry is not null)
            {
                entries.Add(entry);
            }
        }

        foreach (EventInfo eventInfo in type.GetEvents(declaredMembers))
        {
            string? entry = FormatEventEntry(type, eventInfo);
            if (entry is not null)
            {
                entries.Add(entry);
            }
        }
    }

    entries.Sort(StringComparer.Ordinal);
    return entries;
}

static string FormatTypeEntry(Type type)
{
    List<string> modifiers = [FormatTypeAccessibility(type), FormatTypeKind(type)];

    if (!type.IsInterface && !type.IsEnum && !type.IsValueType)
    {
        if (type.IsAbstract && type.IsSealed)
        {
            modifiers.Add("static");
        }
        else
        {
            if (type.IsAbstract)
            {
                modifiers.Add("abstract");
            }

            if (type.IsSealed)
            {
                modifiers.Add("sealed");
            }
        }
    }

    string baseType = type.BaseType is null ? "-" : FormatType(type.BaseType);
    string interfaces = string.Join(",", type.GetInterfaces().Select(FormatType).Order(StringComparer.Ordinal));
    string constraints = FormatGenericConstraints(type.GetGenericArguments().Where(static argument => argument.IsGenericParameter));

    return $"T:{string.Join(' ', modifiers)} {FormatType(type)} base={baseType} interfaces=[{interfaces}]{constraints}";
}

static string FormatConstructorEntry(Type declaringType, ConstructorInfo constructor)
{
    return $"M:{FormatMethodModifiers(constructor)} {FormatType(declaringType)}..ctor({FormatParameters(constructor.GetParameters())})";
}

static string FormatMethodEntry(Type declaringType, MethodInfo method)
{
    string genericArguments = method.IsGenericMethodDefinition
        ? $"<{string.Join(',', method.GetGenericArguments().Select(FormatType))}>"
        : string.Empty;
    string returnModifiers = FormatCustomModifiers(
        method.ReturnParameter.GetRequiredCustomModifiers(),
        method.ReturnParameter.GetOptionalCustomModifiers());
    string constraints = method.IsGenericMethodDefinition
        ? FormatGenericConstraints(method.GetGenericArguments())
        : string.Empty;

    return $"M:{FormatMethodModifiers(method)} {returnModifiers}{FormatType(method.ReturnType)} " +
        $"{FormatType(declaringType)}.{method.Name}{genericArguments}({FormatParameters(method.GetParameters())}){constraints}";
}

static string FormatFieldEntry(Type declaringType, FieldInfo field)
{
    List<string> modifiers = [FormatFieldAccessibility(field), field.IsStatic ? "static" : "instance"];

    if (field.IsInitOnly)
    {
        modifiers.Add("readonly");
    }

    if (field.IsLiteral)
    {
        modifiers.Add("literal");
    }

    string customModifiers = FormatCustomModifiers(field.GetRequiredCustomModifiers(), field.GetOptionalCustomModifiers());
    string constant = field.IsLiteral ? $" value={FormatConstant(field.GetRawConstantValue())}" : string.Empty;

    return $"F:{string.Join(' ', modifiers)} {customModifiers}{FormatType(field.FieldType)} {FormatType(declaringType)}.{field.Name}{constant}";
}

static string? FormatPropertyEntry(Type declaringType, PropertyInfo property)
{
    MethodInfo? getter = property.GetGetMethod(nonPublic: true);
    MethodInfo? setter = property.GetSetMethod(nonPublic: true);
    List<string> accessors = [];

    if (getter is not null && IsVisibleMethod(getter))
    {
        accessors.Add($"get:{FormatAccessor(getter)}");
    }

    if (setter is not null && IsVisibleMethod(setter))
    {
        accessors.Add($"set:{FormatAccessor(setter)}");
    }

    if (accessors.Count == 0)
    {
        return null;
    }

    string customModifiers = FormatCustomModifiers(property.GetRequiredCustomModifiers(), property.GetOptionalCustomModifiers());
    string indexParameters = FormatParameters(property.GetIndexParameters());

    return $"P:{customModifiers}{FormatType(property.PropertyType)} {FormatType(declaringType)}.{property.Name}" +
        $"[{indexParameters}] accessors=[{string.Join(',', accessors)}]";
}

static string? FormatEventEntry(Type declaringType, EventInfo eventInfo)
{
    MethodInfo? addMethod = eventInfo.GetAddMethod(nonPublic: true);
    MethodInfo? removeMethod = eventInfo.GetRemoveMethod(nonPublic: true);
    List<string> accessors = [];

    if (addMethod is not null && IsVisibleMethod(addMethod))
    {
        accessors.Add($"add:{FormatAccessor(addMethod)}");
    }

    if (removeMethod is not null && IsVisibleMethod(removeMethod))
    {
        accessors.Add($"remove:{FormatAccessor(removeMethod)}");
    }

    if (accessors.Count == 0)
    {
        return null;
    }

    return $"E:{FormatType(eventInfo.EventHandlerType ?? typeof(void))} {FormatType(declaringType)}.{eventInfo.Name} " +
        $"accessors=[{string.Join(',', accessors)}]";
}

static string FormatMethodModifiers(MethodBase method)
{
    List<string> modifiers = [FormatMethodAccessibility(method), method.IsStatic ? "static" : "instance"];

    if (method.IsAbstract)
    {
        modifiers.Add("abstract");
    }
    else if (method.IsVirtual)
    {
        modifiers.Add("virtual");
    }

    if (method.IsFinal)
    {
        modifiers.Add("final");
    }

    if ((method.Attributes & MethodAttributes.NewSlot) != 0)
    {
        modifiers.Add("newslot");
    }

    if (method.IsSpecialName)
    {
        modifiers.Add("specialname");
    }

    modifiers.Add($"calling={method.CallingConvention}");
    return string.Join(' ', modifiers);
}

static string FormatAccessor(MethodInfo method)
{
    return $"{FormatMethodAccessibility(method)}:{(method.IsStatic ? "static" : "instance")}";
}

static string FormatParameters(IEnumerable<ParameterInfo> parameters)
{
    return string.Join(',', parameters.OrderBy(static parameter => parameter.Position).Select(FormatParameter));
}

static string FormatParameter(ParameterInfo parameter)
{
    Type parameterType = parameter.ParameterType;
    string mode = string.Empty;

    if (parameterType.IsByRef)
    {
        mode = parameter.IsOut ? "out " : parameter.IsIn ? "in " : "ref ";
        parameterType = parameterType.GetElementType()!;
    }

    string customModifiers = FormatCustomModifiers(
        parameter.GetRequiredCustomModifiers(),
        parameter.GetOptionalCustomModifiers());
    string optional = parameter.IsOptional ? " optional" : string.Empty;
    string defaultValue = parameter.HasDefaultValue ? $" default={FormatConstant(parameter.DefaultValue)}" : string.Empty;

    return $"{mode}{customModifiers}{FormatType(parameterType)}{optional}{defaultValue}";
}

static string FormatCustomModifiers(Type[] requiredModifiers, Type[] optionalModifiers)
{
    List<string> modifiers = [];
    modifiers.AddRange(requiredModifiers.Select(static modifier => $"modreq({FormatType(modifier)})"));
    modifiers.AddRange(optionalModifiers.Select(static modifier => $"modopt({FormatType(modifier)})"));
    return modifiers.Count == 0 ? string.Empty : $"{string.Join(' ', modifiers)} ";
}

static string FormatGenericConstraints(IEnumerable<Type> genericParameters)
{
    List<string> constraints = [];

    foreach (Type parameter in genericParameters.OrderBy(static parameter => parameter.GenericParameterPosition))
    {
        List<string> items = [];
        GenericParameterAttributes attributes = parameter.GenericParameterAttributes;
        GenericParameterAttributes variance = attributes & GenericParameterAttributes.VarianceMask;
        GenericParameterAttributes special = attributes & GenericParameterAttributes.SpecialConstraintMask;

        if (variance == GenericParameterAttributes.Covariant)
        {
            items.Add("out");
        }
        else if (variance == GenericParameterAttributes.Contravariant)
        {
            items.Add("in");
        }

        if ((special & GenericParameterAttributes.ReferenceTypeConstraint) != 0)
        {
            items.Add("class");
        }

        if ((special & GenericParameterAttributes.NotNullableValueTypeConstraint) != 0)
        {
            items.Add("struct");
        }

        if ((special & GenericParameterAttributes.DefaultConstructorConstraint) != 0)
        {
            items.Add("new()");
        }

        items.AddRange(parameter.GetGenericParameterConstraints().Select(FormatType).Order(StringComparer.Ordinal));
        items.AddRange(
            parameter.GetCustomAttributesData()
                .Select(static attribute => $"attr:{attribute.AttributeType.FullName ?? attribute.AttributeType.Name}")
                .Order(StringComparer.Ordinal));

        constraints.Add($"{FormatType(parameter)}:[{string.Join(',', items)}]");
    }

    return constraints.Count == 0 ? string.Empty : $" constraints=[{string.Join(';', constraints)}]";
}

static string FormatType(Type type)
{
    if (type.IsGenericParameter)
    {
        return type.DeclaringMethod is null
            ? $"!{type.GenericParameterPosition}"
            : $"!!{type.GenericParameterPosition}";
    }

    if (type.IsByRef)
    {
        return $"{FormatType(type.GetElementType()!)}&";
    }

    if (type.IsPointer)
    {
        return $"{FormatType(type.GetElementType()!)}*";
    }

    if (type.IsArray)
    {
        int rank = type.GetArrayRank();
        return $"{FormatType(type.GetElementType()!)}[{new string(',', rank - 1)}]";
    }

    if (type.IsGenericType)
    {
        Type definition = type.GetGenericTypeDefinition();
        string definitionName = (definition.FullName ?? definition.Name).Replace('+', '.');
        return $"{definitionName}<{string.Join(',', type.GetGenericArguments().Select(FormatType))}>";
    }

    return (type.FullName ?? type.Name).Replace('+', '.');
}

static string FormatConstant(object? value)
{
    return value switch
    {
        null => "null",
        string text => $"\"{text.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal)}\"",
        char character => $"'{character}'",
        bool boolean => boolean ? "true" : "false",
        float single => single.ToString("R", CultureInfo.InvariantCulture),
        double @double => @double.ToString("R", CultureInfo.InvariantCulture),
        decimal @decimal => @decimal.ToString(CultureInfo.InvariantCulture),
        IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture) ?? value.ToString() ?? string.Empty,
        _ => value.ToString() ?? string.Empty,
    };
}

static bool IsExternallyVisible(Type type)
{
    if (!type.IsNested)
    {
        return type.IsPublic;
    }

    bool nestedVisibility = type.IsNestedPublic || type.IsNestedFamily || type.IsNestedFamORAssem;
    return nestedVisibility && type.DeclaringType is not null && IsExternallyVisible(type.DeclaringType);
}

static bool IsVisibleMethod(MethodBase method)
{
    return method.IsPublic || method.IsFamily || method.IsFamilyOrAssembly;
}

static bool IsVisibleField(FieldInfo field)
{
    return field.IsPublic || field.IsFamily || field.IsFamilyOrAssembly;
}

static string FormatTypeAccessibility(Type type)
{
    if (type.IsNestedFamily)
    {
        return "protected";
    }

    if (type.IsNestedFamORAssem)
    {
        return "protected-internal";
    }

    return "public";
}

static string FormatMethodAccessibility(MethodBase method)
{
    if (method.IsFamily)
    {
        return "protected";
    }

    if (method.IsFamilyOrAssembly)
    {
        return "protected-internal";
    }

    return "public";
}

static string FormatFieldAccessibility(FieldInfo field)
{
    if (field.IsFamily)
    {
        return "protected";
    }

    if (field.IsFamilyOrAssembly)
    {
        return "protected-internal";
    }

    return "public";
}

static string FormatTypeKind(Type type)
{
    if (type.IsInterface)
    {
        return "interface";
    }

    if (type.IsEnum)
    {
        return "enum";
    }

    if (type.IsValueType)
    {
        return "struct";
    }

    if (type.BaseType == typeof(MulticastDelegate))
    {
        return "delegate";
    }

    return "class";
}

sealed class SnapshotLoadContext : AssemblyLoadContext
{
    private readonly string assemblyDirectory;

    public SnapshotLoadContext(string assemblyPath)
        : base(isCollectible: true)
    {
        assemblyDirectory = Path.GetDirectoryName(assemblyPath)
            ?? throw new ArgumentException("Assembly path must have a directory.", nameof(assemblyPath));
    }

    protected override Assembly? Load(AssemblyName assemblyName)
    {
        if (string.IsNullOrWhiteSpace(assemblyName.Name))
        {
            return null;
        }

        string candidate = Path.Combine(assemblyDirectory, $"{assemblyName.Name}.dll");
        return File.Exists(candidate) ? LoadFromAssemblyPath(candidate) : null;
    }
}
